spring:
  application:
    name: TranData
    
app:
  constants:
    ws:
      tran-data-url: https://trxapitest.credable.io/service/transactionWsdl.wsdl
    basic-auth:
      username: user1
      password: P@ssword